# 固定值
apiVersion: v2
# 组件名称
name: pytorch-operator
# chart 描述
description: A helm chart for pytorch-operator addon
# 固定值
type: application
# 组件版本号
appVersion: v2.0.0-rc.1
# chart 版本号，与组件版本号 appVersion 字段保持一致
version: v2.0.0-rc.1
